# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5s",
  "iPhone X",
  "iPad Pro (9.7-inch)",
  "iPad Pro (12.9-inch)",
  # "iPad Pro (10.5-inch)", # not supported in iTunes Connect
])

languages([
  "en-US",
  "fr-FR",
  "it",
  "nl-NL",
  "zh-Hans",
  "zh-Hant",
])

ENV["FASTLANE_SNAPSHOT"] = "YES"

# The name of the scheme which contains the UI Tests
scheme "Screenshots"

configuration "Debug"

clear_previous_screenshots true
erase_simulator true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
