# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Padiddle")
  end

  desc "Take screenshots for the App Store"
  lane :screenshots do
    ENV["FASTLANE_SNAPSHOT"] = "YES"
    scan(
      scheme: "Screenshots",
      configuration: "Debug",
      derived_data_path: ".build/DerivedData"
    )
    snapshot(
      scheme: "Screenshots",
      configuration: "Debug",
      test_without_building: true,
      derived_data_path: ".build/DerivedData",
      clear_previous_screenshots: true,
      erase_simulator: true,
      devices: [
        "iPhone SE (3rd generation)",
        "iPhone 14",
        "iPad Air 11-inch (M3)",
      ],
      languages: [
        "en-US",
        "fr-FR",
        "it",
        "nl-NL",
        "zh-Hans",
        "zh-Hant",
      ],
    )
  end

  desc "Take screenshots for the website"
  lane :screenshotsForWebsite do
    ENV["FASTLANE_SNAPSHOT"] = "YES"
    scan(
      scheme: "Screenshots",
      configuration: "Debug",
      derived_data_path: ".build/DerivedData"
    )
    snapshot(
      scheme: "ScreenshotsForWebsite",
      configuration: "Debug",
      test_without_building: true,
      derived_data_path: ".build/DerivedData",
      clear_previous_screenshots: true,
      erase_simulator: true,
      devices: [
        "iPhone 14",
        "iPad Pro (11-inch) (3rd generation)",
      ],
      languages: ["en-US"],
      output_directory: "fastlane/screenshots_for_website"
    )
    frameit
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
    scheme: "Padiddle",
    include_symbols: true,
    include_bitcode: true
    )
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    snapshot
    gym(
    scheme: "Padiddle",
    include_symbols: true,
    include_bitcode: true,
    export_xcargs: '-allowProvisioningUpdates'
    )
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
