disabled_rules: # rule identifiers to exclude from running
  - file_length
  - function_body_length
  - line_length
  - identifier_name

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - last_where
  - legacy_random
  - multiline_arguments
  - operator_usage_whitespace
  - redundant_objc_attribute
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unused_control_flow_label
  - vertical_whitespace

excluded:
  - Carthage
  - Pods
  - Screenshots/SnapshotHelper.swift

file_length:
  warning: 450
  error: 500

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true
