platform :ios, '10.0'
  use_frameworks!

  # Pods for Padiddle
target 'Padiddle' do  
  pod 'SwiftGen'
  pod 'Anchorage'
  pod 'SimulatorStatusMagic', :configurations => ['Debug']

  target 'PadiddleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PadiddleUITests' do
    inherit! :search_paths
    # Pods for UI testing
  end

end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Padiddle/Pods-Padiddle-acknowledgements.plist', 'Padiddle/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
