source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
  use_frameworks!

  # Pods for Padiddle
target 'Padiddle' do
  pod 'Anchorage'
  pod 'BonMot'
  pod 'SwiftGen'
  pod 'SwiftLint'
end

target 'PadiddleTests' do
end

target 'PadiddleUITests' do
end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Padiddle/Pods-Padiddle-acknowledgements.plist', 'Padiddle/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
