platform :ios, '10.0'
use_frameworks!

target 'Padiddle' do  
  pod 'SwiftGen'
  pod 'Anchorage', :git => 'git@github.com:Raizlabs/Anchorage.git', :commit => '11ae636b97ba83163b49addd679d11aaf312eabd'
  pod 'SimulatorStatusMagic', :configurations => ['Debug']
end

target 'PadiddleTests' do

end

target 'PadiddleUITests' do

end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-Padiddle/Pods-Padiddle-acknowledgements.plist', 'Padiddle/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
