# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  # "iPhone 6 Plus",
  # "iPhone 5",
  # "iPhone 4s",
  "iPad Retina",
  # "iPad Pro"
])

languages([
  "en-US",
  "fr-Fr",
  "it-It",
  "zh-Hans",
  "zh-Hant",
])

ENV["FASTLANE_SNAPSHOT"] = "1"

# The name of the scheme which contains the UI Tests
scheme "Screenshots"

configuration "Debug"

# Where should the resulting screenshots be stored?
output_directory "../Captured Screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
